/*
 * Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

import * as moment from "moment";


/**
 * @class
 * Initializes a new instance of the Model1 class.
 * @constructor
 * @member {string} email User email account.
 *
 * @member {string} password User password
 *
 */
export interface Model1 {
  email: string;
  password: string;
}
