package silica

// Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

// Model1 is
type Model1 struct {
    Email *string `json:"email,omitempty"`
    Password *string `json:"password,omitempty"`
}

