// Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace silica
{
    using Models;
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>
    /// Extension methods for GetSystemApi.
    /// </summary>
    public static partial class GetSystemApiExtensions
    {
            /// <summary>
            /// API Heartbeat Monitoring
            /// </summary>
            /// <remarks>
            /// Endpoint used for Heartbeat Monitoring. Monitoring will use this endpoint
            /// to check if the API is up and available.
            /// </remarks>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='aPIKey'>
            /// Client API Key
            /// </param>
            public static void PingApi(this IGetSystemApi operations, string aPIKey)
            {
                operations.PingApiAsync(aPIKey).GetAwaiter().GetResult();
            }

            /// <summary>
            /// API Heartbeat Monitoring
            /// </summary>
            /// <remarks>
            /// Endpoint used for Heartbeat Monitoring. Monitoring will use this endpoint
            /// to check if the API is up and available.
            /// </remarks>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='aPIKey'>
            /// Client API Key
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task PingApiAsync(this IGetSystemApi operations, string aPIKey, CancellationToken cancellationToken = default(CancellationToken))
            {
                (await operations.PingApiWithHttpMessagesAsync(aPIKey, null, cancellationToken).ConfigureAwait(false)).Dispose();
            }

    }
}
