// Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace silica
{
    using Models;
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>
    /// Extension methods for GetSystemGeneratesdkApi.
    /// </summary>
    public static partial class GetSystemGeneratesdkApiExtensions
    {
            /// <summary>
            /// API Heartbeat Monitoring
            /// </summary>
            /// <remarks>
            /// Endpoint used for Heartbeat Monitoring. Monitoring will use this endpoint
            /// to check if the API is up and available.
            /// </remarks>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='aPIKey'>
            /// Client API Key
            /// </param>
            /// <param name='swaggerJSONurl'>
            /// Url path to swagger.json file
            /// </param>
            /// <param name='language'>
            /// Development language to generate SDK for. Possible values include:
            /// 'csharp', 'go', 'java', 'nodejs', 'python', 'ruby'
            /// </param>
            /// <param name='namespaceParameter'>
            /// User selected namespace
            /// </param>
            public static void KeySwaggerjsonurlLanguageNamespace(this IGetSystemGeneratesdkApi operations, string aPIKey, string swaggerJSONurl, string language, string namespaceParameter)
            {
                operations.KeySwaggerjsonurlLanguageNamespaceAsync(aPIKey, swaggerJSONurl, language, namespaceParameter).GetAwaiter().GetResult();
            }

            /// <summary>
            /// API Heartbeat Monitoring
            /// </summary>
            /// <remarks>
            /// Endpoint used for Heartbeat Monitoring. Monitoring will use this endpoint
            /// to check if the API is up and available.
            /// </remarks>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='aPIKey'>
            /// Client API Key
            /// </param>
            /// <param name='swaggerJSONurl'>
            /// Url path to swagger.json file
            /// </param>
            /// <param name='language'>
            /// Development language to generate SDK for. Possible values include:
            /// 'csharp', 'go', 'java', 'nodejs', 'python', 'ruby'
            /// </param>
            /// <param name='namespaceParameter'>
            /// User selected namespace
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task KeySwaggerjsonurlLanguageNamespaceAsync(this IGetSystemGeneratesdkApi operations, string aPIKey, string swaggerJSONurl, string language, string namespaceParameter, CancellationToken cancellationToken = default(CancellationToken))
            {
                (await operations.KeySwaggerjsonurlLanguageNamespaceWithHttpMessagesAsync(aPIKey, swaggerJSONurl, language, namespaceParameter, null, cancellationToken).ConfigureAwait(false)).Dispose();
            }

    }
}
