// Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace silica
{
    using Microsoft.Rest;
    using Models;
    using System.Collections;
    using System.Collections.Generic;
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>
    /// GetSystemGeneratesdkApi operations.
    /// </summary>
    public partial interface IGetSystemGeneratesdkApi
    {
        /// <summary>
        /// API Heartbeat Monitoring
        /// </summary>
        /// <remarks>
        /// Endpoint used for Heartbeat Monitoring. Monitoring will use this
        /// endpoint to check if the API is up and available.
        /// </remarks>
        /// <param name='aPIKey'>
        /// Client API Key
        /// </param>
        /// <param name='swaggerJSONurl'>
        /// Url path to swagger.json file
        /// </param>
        /// <param name='language'>
        /// Development language to generate SDK for. Possible values include:
        /// 'csharp', 'go', 'java', 'nodejs', 'python', 'ruby'
        /// </param>
        /// <param name='namespaceParameter'>
        /// User selected namespace
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        /// <exception cref="Microsoft.Rest.HttpOperationException">
        /// Thrown when the operation returned an invalid status code
        /// </exception>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown when a required parameter is null
        /// </exception>
        Task<HttpOperationResponse> KeySwaggerjsonurlLanguageNamespaceWithHttpMessagesAsync(string aPIKey, string swaggerJSONurl, string language, string namespaceParameter, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));
    }
}
