# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from .mastertemplate import MASTERTEMPLATE
from .version import VERSION

__all__ = ['MASTERTEMPLATE']

__version__ = VERSION

