/**
 * Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package silica.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The Model1 model.
 */
public class Model1 {
    /**
     * User email account.
     */
    @JsonProperty(value = "email", required = true)
    private String email;

    /**
     * User password.
     */
    @JsonProperty(value = "password", required = true)
    private String password;

    /**
     * Get the email value.
     *
     * @return the email value
     */
    public String email() {
        return this.email;
    }

    /**
     * Set the email value.
     *
     * @param email the email value to set
     * @return the Model1 object itself.
     */
    public Model1 withEmail(String email) {
        this.email = email;
        return this;
    }

    /**
     * Get the password value.
     *
     * @return the password value
     */
    public String password() {
        return this.password;
    }

    /**
     * Set the password value.
     *
     * @param password the password value to set
     * @return the Model1 object itself.
     */
    public Model1 withPassword(String password) {
        this.password = password;
        return this;
    }

}
