// Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

/**
 * This package contains the models classes for MASTERTEMPLATE.
 * Master API Teplate with cross cutting concerns baked into the template.
 */
package silica.models;
