# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class Model1(Model):
    """Model1.

    :param email: User email account.
    :type email: str
    :param password: User password
    :type password: str
    """

    _validation = {
        'email': {'required': True, 'max_length': 50},
        'password': {'required': True, 'max_length': 200},
    }

    _attribute_map = {
        'email': {'key': 'email', 'type': 'str'},
        'password': {'key': 'password', 'type': 'str'},
    }

    def __init__(self, email, password):
        self.email = email
        self.password = password
